#!/usr/bin/env python3
"""Generate src/rooms/index.js from built room assets + the world graph.

For each built room: tile rows from the collision mask, spawn, and exits
with resolved targets and arrival tiles (center of the paired edge strip in
the target room, nudged inward).
"""
import json
import os

import numpy as np
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
AP = os.path.join(ROOT, 'tools', 'art-pipeline')
OPP = {'n': 's', 's': 'n', 'w': 'e', 'e': 'w'}


def load_room(name):
    ij = os.path.join(ROOT, 'assets', 'rooms', f'{name}.instances.json')
    cp = os.path.join(ROOT, 'assets', 'rooms', f'{name}.collision.png')
    if not (os.path.exists(ij) and os.path.exists(cp)):
        return None
    d = json.load(open(ij))
    col = np.asarray(Image.open(cp).convert('L').resize((640, 448), Image.NEAREST)) > 127
    rows = []
    for ty in range(28):
        row = ''
        for tx in range(40):
            row += '.' if col[ty * 16:(ty + 1) * 16, tx * 16:(tx + 1) * 16].mean() > 0.4 else '#'
        rows.append(row)
    return {'data': d, 'rows': rows}


def arrival_tile(target_room, edge_in_target):
    """Arrival point: center of the target's strip on edge_in_target, nudged inward."""
    for e in target_room['data'].get('exits', []):
        if e['edge'] == edge_in_target:
            x0, y0, x1, y1 = e['rect']
            cx, cy = (x0 + x1) // 2, (y0 + y1) // 2
            nudge = 28
            if edge_in_target == 'n':
                cy = y1 + nudge
            elif edge_in_target == 's':
                cy = y0 - nudge
            elif edge_in_target == 'w':
                cx = x1 + nudge
            else:
                cx = x0 - nudge
            return max(1, min(38, round(cx / 16))), max(1, min(26, round(cy / 16)))
    sp = target_room['data']['spawn']
    return round(sp[0] / 16), round(sp[1] / 16)


def main():
    cfg = json.load(open(os.path.join(AP, 'rooms.json')))
    graph = dict(cfg['rooms'])
    graph['anchorroom'] = cfg['anchors']['anchorroom']
    for k, v in cfg.get('interiors', {}).items():
        graph[k] = {'exits': {'s': v['parent']}}
    doors_f = os.path.join(AP, 'doors.json')
    doors = json.load(open(doors_f)) if os.path.exists(doors_f) else {}
    built = {}
    for name in graph:
        r = load_room(name)
        if r:
            built[name] = r
    out = {}
    for name, r in built.items():
        exits = []
        for e in r['data'].get('exits', []):
            to = graph[name]['exits'].get(e['edge'])
            if not to or (to != 'overworld' and to not in built):
                continue
            if to == 'overworld':
                tx, ty = 38, 26
                to_rect = None
            else:
                tx, ty = arrival_tile(built[to], OPP[e['edge']])
                to_rect = None
                for te in built[to]['data'].get('exits', []):
                    if te['edge'] == OPP[e['edge']]:
                        to_rect = te['rect']
            # interior return exits arrive at the parent's DOOR, not an edge
            pdoor = next((dd for dd in doors.get(to, []) if dd['to'] == name), None)
            if e['edge'] == 's' and pdoor:
                to_rect = pdoor['rect']
                tx = max(1, min(38, round((pdoor['rect'][0] + pdoor['rect'][2]) / 2 / 16)))
                ty = max(1, min(26, round((pdoor['rect'][3] + 14) / 16)))
            exits.append({'edge': e['edge'], 'rect': e['rect'], 'to': to,
                          'tx': tx, 'ty': ty, 'toRect': to_rect})
        for dd in doors.get(name, []):
            if dd['to'] not in built:
                continue
            dx0, dy0, dx1, dy1 = dd['rect']
            trig = [dx0, dy1 - 4, dx1, dy1 + 16]
            itx, ity = arrival_tile(built[dd['to']], 's')
            srect = None
            for te in built[dd['to']]['data'].get('exits', []):
                if te['edge'] == 's':
                    srect = te['rect']
            exits.append({'edge': 'door', 'rect': trig, 'to': dd['to'],
                          'tx': itx, 'ty': ity, 'toRect': srect})
        out[name] = {'id': name, 'plate': f'rooms/{name}.jpg', 'rows': r['rows'],
                     'spawn': [round(v) for v in r['data']['spawn']], 'exits': exits}
    js = ('// GENERATED by tools/art-pipeline/gen_rooms_index.py - do not hand-edit.\n'
          '// Plate-room registry: tile rows from collision, spawns, edge exits.\n'
          'export const PLATE_ROOMS = ' + json.dumps(out, indent=1) + ';\n'
          'export const PLATE_ROOM_NAMES = ' + json.dumps(sorted(out)) + ';\n')
    open(os.path.join(ROOT, 'src', 'rooms', 'index.js'), 'w').write(js)
    print(f'src/rooms/index.js: {len(out)} rooms, '
          f'{sum(len(v["exits"]) for v in out.values())} wired exits')


if __name__ == '__main__':
    main()
